apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: deliverytn-sandbox
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30092
    hostPort: 30092
    listenAddress: "0.0.0.0"
    protocol: tcp
- role: worker